### ISSUE TITLE
Support running in the browser (without NodeJS api)

### ISSUE THREAD

**Issue by x87** [azu/korefile#6]
Hi! Thanks for your library! 

I use it in my small project and it works very well. However I had to adjust it for my use case. Here it is. 

My application is an Angular app and it runs entirely in the browser. I was unable to use KoreFile initially as it makes use of some NodeJS API such as `process` and `Buffer`. It does not seem like a strict requirement though. I forked the lib and removed/replaced those apis. 

It would be quite nice if you can support it on the library level via the public API, or maybe consider doing a platform-independent version that would work well both in NodeJS app and a browser (webpack bundle).

Thanks for your time.

**Comment by azu** [comment]
KoreFile provide `browser` filed.
https://github.com/azu/korefile/blob/cb8fd416d8aa86fd675123f711414e63746c6579/package.json#L28
I think that almost bundler like webpack, rollup support it.

https://webpack.js.org/configuration/resolve/#resolvemainfields

Can you tell me an actual error?

**Comment by x87** [comment]
@azu when I include the library in my angular app I get the error `ReferenceError: process is not defined`.
https://github.com/azu/korefile/blob/master/src/GitHubAdaptor.ts#L10

also Buffer.from is a NodeJS api: https://github.com/azu/korefile/blob/master/src/GitHubAdaptor.ts#L142 in the browser you would get ReferenceError: Buffer is not defined

I removed `process` and replaced `Buffer.from` with [atob](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob) and it worked.

**Comment by azu** [comment]
Thanks for the details.

Angular compiler may require polyfills for Node.js core modules manually.
[ERROR ReferenceError: Buffer is not defined · Issue #2 · agoncal/swagger-ui-angular6](https://github.com/agoncal/swagger-ui-angular6/issues/2)

It is reasonable that remove the dependencies of `Buffer` and `process.`

- Buffer can be replaced with [js-base64](https://www.npmjs.com/package/js-base64)
- process can be removed from browser bundle or use `typeof process !== undefined && process.env.GITHUB_TOKEN`

**Comment by x87** [comment]
It's your choice, but I would probably make the token mandatory on `GitCommitPushOptions` (same as `owner` and `repo`) so the `process` could be dropped.
